import Vue from 'vue'
import { Drawer, PageHeader, Tooltip, Backtop, Notification, MessageBox, TableColumn, Table, Option, DatePicker, Select, Dialog, Avatar, Pagination, Message, FormItem, Form, Breadcrumb, BreadcrumbItem, TabPane, Tabs, Tag, Badge, Image, Footer, Card, Input, Button, Container, Header, Main, Menu, MenuItem, MenuItemGroup, Submenu, Row, Col } from 'element-ui'
Vue.use(Drawer)
Vue.use(PageHeader)
Vue.use(Tooltip)
Vue.use(Backtop)
Vue.use(Table)
Vue.use(TableColumn)
Vue.use(Option)
Vue.use(DatePicker)
Vue.use(Select)
Vue.use(Tabs)
Vue.use(Card)
Vue.use(Button)
Vue.use(Input)
Vue.use(Container)
Vue.use(Header)
Vue.use(Main)
Vue.use(Menu)
Vue.use(MenuItem)
Vue.use(MenuItemGroup)
Vue.use(Submenu)
Vue.use(Row)
Vue.use(Col)
Vue.use(Footer)
Vue.use(Image)
Vue.use(Badge)
Vue.use(Tag)
Vue.use(TabPane)
Vue.use(BreadcrumbItem)
Vue.use(Breadcrumb)
Vue.use(Form)
Vue.use(FormItem)
Vue.use(Pagination)
Vue.use(Avatar)
Vue.use(Dialog)
Vue.prototype.$message = Message
Vue.prototype.$messageBox = MessageBox
Vue.prototype.$notify = Notification
